raw_ecg = readtable("sinus_S62_run000001_raw.csv");
predictions = readtable("sinus_S62_run000001_ecgdeli_prediction.csv");

timestep = 2;
end_time = width(raw_ecg)*timestep;
time_array = 2:timestep:end_time;

number_of_beats = height(predictions)/12;

style = '-';
color = [0 0 0];
lw = 1.2;

lim1 = predictions{13,"p_onset_ms"} - 100;
lim2 = predictions{13,"t_offset_ms"} + 200;

subplot(3,4,1), plot(time_array, raw_ecg{1,:}, style, 'Color', color, 'LineWidth',lw), ...
    hold on, plot(predictions{13,"qrs_onset_ms"}, raw_ecg{1,predictions{13,"qrs_onset"}}, '.', 'MarkerSize', 15), ...
    hold on, plot(predictions{13,"qrs_offset_ms"}, raw_ecg{1,predictions{13,"qrs_offset"}}, '.', 'MarkerSize', 15), ...
    hold on, plot(predictions{13,"t_onset_ms"}, raw_ecg{1,predictions{13,"t_onset"}}, '.', 'MarkerSize', 15), ...
    hold on, plot(predictions{13,"t_peak_ms"}, raw_ecg{1,predictions{13,"t_peak"}}, '.', 'MarkerSize', 15), ...
    hold on, plot(predictions{13,"t_offset_ms"}, raw_ecg{1,predictions{13,"t_offset"}}, '.', 'MarkerSize', 15), ...
    grid on, xlim([lim1 lim2]), title("I")
subplot(3,4,5), plot(time_array, raw_ecg{2,:}, style, 'Color', color, 'LineWidth',lw), ...
    hold on, plot(predictions{26,"qrs_onset_ms"}, raw_ecg{2,predictions{26,"qrs_onset"}}, '.', 'MarkerSize', 15), ...
    hold on, plot(predictions{26,"qrs_offset_ms"}, raw_ecg{2,predictions{26,"qrs_offset"}}, '.', 'MarkerSize', 15), ...
    hold on, plot(predictions{26,"t_onset_ms"}, raw_ecg{2,predictions{26,"t_onset"}}, '.', 'MarkerSize', 15), ...
    hold on, plot(predictions{26,"t_peak_ms"}, raw_ecg{2,predictions{26,"t_peak"}}, '.', 'MarkerSize', 15), ...
    hold on, plot(predictions{26,"t_offset_ms"}, raw_ecg{2,predictions{26,"t_offset"}}, '.', 'MarkerSize', 15), ...
    grid on, xlim([lim1 lim2]), title("II")
subplot(3,4,9), plot(time_array, raw_ecg{3,:}, style, 'Color', color, 'LineWidth',lw), ...
    hold on, plot(predictions{39,"qrs_onset_ms"}, raw_ecg{3,predictions{39,"qrs_onset"}}, '.', 'MarkerSize', 15), ...
    hold on, plot(predictions{39,"qrs_offset_ms"}, raw_ecg{3,predictions{39,"qrs_offset"}}, '.', 'MarkerSize', 15), ...
    hold on, plot(predictions{39,"t_onset_ms"}, raw_ecg{3,predictions{39,"t_onset"}}, '.', 'MarkerSize', 15), ...
    hold on, plot(predictions{39,"t_peak_ms"}, raw_ecg{3,predictions{39,"t_peak"}}, '.', 'MarkerSize', 15), ...
    hold on, plot(predictions{39,"t_offset_ms"}, raw_ecg{3,predictions{39,"t_offset"}}, '.', 'MarkerSize', 15), ...
    grid on, xlim([lim1 lim2]), title("III")
subplot(3,4,2), plot(time_array, raw_ecg{4,:}, style, 'Color', color, 'LineWidth',lw), ...
    hold on, plot(predictions{52,"qrs_onset_ms"}, raw_ecg{4,predictions{52,"qrs_onset"}}, '.', 'MarkerSize', 15), ...
    hold on, plot(predictions{52,"qrs_offset_ms"}, raw_ecg{4,predictions{52,"qrs_offset"}}, '.', 'MarkerSize', 15), ...
    hold on, plot(predictions{52,"t_onset_ms"}, raw_ecg{4,predictions{52,"t_onset"}}, '.', 'MarkerSize', 15), ...
    hold on, plot(predictions{52,"t_peak_ms"}, raw_ecg{4,predictions{52,"t_peak"}}, '.', 'MarkerSize', 15), ...
    hold on, plot(predictions{52,"t_offset_ms"}, raw_ecg{4,predictions{52,"t_offset"}}, '.', 'MarkerSize', 15), ...
    grid on, xlim([lim1 lim2]), title("aVR")
subplot(3,4,6), plot(time_array, raw_ecg{5,:}, style, 'Color', color, 'LineWidth',lw), ...
    hold on, plot(predictions{65,"qrs_onset_ms"}, raw_ecg{5,predictions{65,"qrs_onset"}}, '.', 'MarkerSize', 15), ...
    hold on, plot(predictions{65,"qrs_offset_ms"}, raw_ecg{5,predictions{65,"qrs_offset"}}, '.', 'MarkerSize', 15), ...
    hold on, plot(predictions{65,"t_onset_ms"}, raw_ecg{5,predictions{65,"t_onset"}}, '.', 'MarkerSize', 15), ...
    hold on, plot(predictions{65,"t_peak_ms"}, raw_ecg{5,predictions{65,"t_peak"}}, '.', 'MarkerSize', 15), ...
    hold on, plot(predictions{65,"t_offset_ms"}, raw_ecg{5,predictions{65,"t_offset"}}, '.', 'MarkerSize', 15), ...
    grid on, xlim([lim1 lim2]), title("aVL")
subplot(3,4,10), plot(time_array, raw_ecg{6,:}, style, 'Color', color, 'LineWidth',lw), ...
    hold on, plot(predictions{78,"qrs_onset_ms"}, raw_ecg{6,predictions{78,"qrs_onset"}}, '.', 'MarkerSize', 15), ...
    hold on, plot(predictions{78,"qrs_offset_ms"}, raw_ecg{6,predictions{78,"qrs_offset"}}, '.', 'MarkerSize', 15), ...
    hold on, plot(predictions{78,"t_onset_ms"}, raw_ecg{6,predictions{78,"t_onset"}}, '.', 'MarkerSize', 15), ...
    hold on, plot(predictions{78,"t_peak_ms"}, raw_ecg{6,predictions{78,"t_peak"}}, '.', 'MarkerSize', 15), ...
    hold on, plot(predictions{78,"t_offset_ms"}, raw_ecg{6,predictions{78,"t_offset"}}, '.', 'MarkerSize', 15), ...
    grid on, xlim([lim1 lim2]), title("aVF")
subplot(3,4,3), plot(time_array, raw_ecg{7,:}, style, 'Color', color, 'LineWidth',lw), ...
    hold on, plot(predictions{91,"qrs_onset_ms"}, raw_ecg{7,predictions{91,"qrs_onset"}}, '.', 'MarkerSize', 15), ...
    hold on, plot(predictions{91,"qrs_offset_ms"}, raw_ecg{7,predictions{91,"qrs_offset"}}, '.', 'MarkerSize', 15), ...
    hold on, plot(predictions{91,"t_onset_ms"}, raw_ecg{7,predictions{91,"t_onset"}}, '.', 'MarkerSize', 15), ...
    hold on, plot(predictions{91,"t_peak_ms"}, raw_ecg{7,predictions{91,"t_peak"}}, '.', 'MarkerSize', 15), ...
    hold on, plot(predictions{91,"t_offset_ms"}, raw_ecg{7,predictions{91,"t_offset"}}, '.', 'MarkerSize', 15), ...
    grid on, xlim([lim1 lim2]), title("V1")
subplot(3,4,7), plot(time_array, raw_ecg{8,:}, style, 'Color', color, 'LineWidth',lw), ...
    hold on, plot(predictions{104,"qrs_onset_ms"}, raw_ecg{8,predictions{104,"qrs_onset"}}, '.', 'MarkerSize', 15), ...
    hold on, plot(predictions{104,"qrs_offset_ms"}, raw_ecg{8,predictions{104,"qrs_offset"}}, '.', 'MarkerSize', 15), ...
    hold on, plot(predictions{104,"t_onset_ms"}, raw_ecg{8,predictions{104,"t_onset"}}, '.', 'MarkerSize', 15), ...
    hold on, plot(predictions{104,"t_peak_ms"}, raw_ecg{8,predictions{104,"t_peak"}}, '.', 'MarkerSize', 15), ...
    hold on, plot(predictions{104,"t_offset_ms"}, raw_ecg{8,predictions{104,"t_offset"}}, '.', 'MarkerSize', 15), ...
    grid on, xlim([lim1 lim2]), title("V2")
subplot(3,4,11), plot(time_array, raw_ecg{9,:}, style, 'Color', color, 'LineWidth',lw), ...
    hold on, plot(predictions{117,"qrs_onset_ms"}, raw_ecg{9,predictions{117,"qrs_onset"}}, '.', 'MarkerSize', 15), ...
    hold on, plot(predictions{117,"qrs_offset_ms"}, raw_ecg{9,predictions{117,"qrs_offset"}}, '.', 'MarkerSize', 15), ...
    hold on, plot(predictions{117,"t_onset_ms"}, raw_ecg{9,predictions{117,"t_onset"}}, '.', 'MarkerSize', 15), ...
    hold on, plot(predictions{117,"t_peak_ms"}, raw_ecg{9,predictions{117,"t_peak"}}, '.', 'MarkerSize', 15), ...
    hold on, plot(predictions{117,"t_offset_ms"}, raw_ecg{9,predictions{117,"t_offset"}}, '.', 'MarkerSize', 15), ...
    grid on, xlim([lim1 lim2]), title("V3")
subplot(3,4,4), plot(time_array, raw_ecg{10,:}, style, 'Color', color, 'LineWidth',lw), ...
    hold on, plot(predictions{130,"qrs_onset_ms"}, raw_ecg{10,predictions{130,"qrs_onset"}}, '.', 'MarkerSize', 15), ...
    hold on, plot(predictions{130,"qrs_offset_ms"}, raw_ecg{10,predictions{130,"qrs_offset"}}, '.', 'MarkerSize', 15), ...
    hold on, plot(predictions{130,"t_onset_ms"}, raw_ecg{10,predictions{130,"t_onset"}}, '.', 'MarkerSize', 15), ...
    hold on, plot(predictions{130,"t_peak_ms"}, raw_ecg{10,predictions{130,"t_peak"}}, '.', 'MarkerSize', 15), ...
    hold on, plot(predictions{130,"t_offset_ms"}, raw_ecg{10,predictions{130,"t_offset"}}, '.', 'MarkerSize', 15), ...
    grid on, xlim([lim1 lim2]), title("V4")
subplot(3,4,8), plot(time_array, raw_ecg{11,:}, style, 'Color', color, 'LineWidth',lw), ...
    hold on, plot(predictions{143,"qrs_onset_ms"}, raw_ecg{11,predictions{143,"qrs_onset"}}, '.', 'MarkerSize', 15), ...
    hold on, plot(predictions{143,"qrs_offset_ms"}, raw_ecg{11,predictions{143,"qrs_offset"}}, '.', 'MarkerSize', 15), ...
    hold on, plot(predictions{143,"t_onset_ms"}, raw_ecg{11,predictions{143,"t_onset"}}, '.', 'MarkerSize', 15), ...
    hold on, plot(predictions{143,"t_peak_ms"}, raw_ecg{11,predictions{143,"t_peak"}}, '.', 'MarkerSize', 15), ...
    hold on, plot(predictions{143,"t_offset_ms"}, raw_ecg{11,predictions{143,"t_offset"}}, '.', 'MarkerSize', 15), ...
    grid on, xlim([lim1 lim2]), title("V5")
subplot(3,4,12), plot(time_array, raw_ecg{12,:}, style, 'Color', color, 'LineWidth',lw), ...
    hold on, plot(predictions{156,"qrs_onset_ms"}, raw_ecg{12,predictions{156,"qrs_onset"}}, '.', 'MarkerSize', 15), ...
    hold on, plot(predictions{156,"qrs_offset_ms"}, raw_ecg{12,predictions{156,"qrs_offset"}}, '.', 'MarkerSize', 15), ...
    hold on, plot(predictions{156,"t_onset_ms"}, raw_ecg{12,predictions{156,"t_onset"}}, '.', 'MarkerSize', 15), ...
    hold on, plot(predictions{156,"t_peak_ms"}, raw_ecg{12,predictions{156,"t_peak"}}, '.', 'MarkerSize', 15), ...
    hold on, plot(predictions{156,"t_offset_ms"}, raw_ecg{12,predictions{156,"t_offset"}}, '.', 'MarkerSize', 15), ...
    grid on, xlim([lim1 lim2]), title("V6")